name = "COE751"
uuid = "61aba8c1-e5ae-4da1-bc86-af753446aea1"
authors = ["viniciusjusten <viniciusjusten@psr-inc.com>"]
version = "0.1.0"

[deps]
EnumX = "4e289a0a-7415-4d19-859d-a7e5c4648b56"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
EnumX = "1.0.7"
SparseArrays = "1.11.0"
Test = "1.11.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
